name: Build 4.7.0

on:
  workflow_dispatch:
  push:
    branches:
      - "fix-host-longest-match-4.7.0"

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install .NET Framework 4 Targeting Pack
        shell: powershell
        run: |
          choco install netfx-4.0-devpack -y

      - name: Build net2.0
        shell: powershell
        run: |
          msbuild .\shadowsocks-csharp\shadowsocks-csharp.csproj `
          /t:Build `
          /p:Configuration=Release `
          /p:DefineConstants=_DOTNET_2_0 `
          /m

      - name: Build net4.0
        shell: powershell
        run: |
          msbuild .\shadowsocks-csharp\shadowsocks-csharp.csproj `
          /t:Build `
          /p:Configuration=Release `
          /p:DefineConstants=_DOTNET_4_0 `
          /m

      - name: Package
        shell: powershell
        run: |
          mkdir artifact\net2.0
          mkdir artifact\net4.0

          Copy-Item `
          .\shadowsocks-csharp\bin\2.0\Release\* `
          artifact\net2.0 `
          -Recurse `
          -Force

          Copy-Item `
          .\shadowsocks-csharp\bin\4.0\Release\* `
          artifact\net4.0 `
          -Recurse `
          -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShadowsocksR-4.7.0-net2-net4
          path: artifact
